services:
  eva04_app:
    build: .
    image: eva04:latest
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:-testkey}
      - MODEL_PATH=/app/models/modelo_demanda_v1.joblib
      - METADATA_PATH=/app/models/metadata.json
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./outputs:/app/outputs:rw
      - ./models:/app/models:rw
    command: uvicorn src.serving.api_endpoints_only:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 10G
        reservations:
          cpus: '4.0'
          memory: 4G
